version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/alexandriastech/circlei-and-uilicious/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  run-uilicious:
    environment:
      <access-key>: GPRrihvU5XCVeiaw9Vy5p3
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Hello, World!
          - npm install -g uilicious-cli
          - uilicious-cli run "My First Project" "myfirstTest" --key <access-key>
                   

workflows:
  my-custom-workflow:
    jobs:
      - run-uilicious
